"""initial user/workspace/node tables

Revision ID: 121af3e6805c
Revises: 
Create Date: 2026-09-11 10:34:47.117274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '121af3e6805c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_kind', sa.String(), nullable=False),
    sa.Column('schema_source', sa.Text(), nullable=False),
    sa.Column('raw_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('encrypted_credential', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path_template', sa.String(), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('declared_request_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('declared_response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node')
    op.drop_table('workspace')
    op.drop_table('user')
    # ### end Alembic commands ###
