"""add workspace.credential_header_name

Revision ID: 9b348fd67dbb
Revises: f2f324544bfc
Create Date: 2026-09-12 16:58:23.509215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b348fd67dbb'
down_revision: Union[str, Sequence[str], None] = 'f2f324544bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('credential_header_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'credential_header_name')
    # ### end Alembic commands ###
