"""add request, response, drift_finding tables and workspace.base_path

Revision ID: f2f324544bfc
Revises: f41f792459e6
Create Date: 2026-09-11 17:01:19.500066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2f324544bfc'
down_revision: Union[str, Sequence[str], None] = 'f41f792459e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_finding',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('response_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workspace', sa.Column('base_path', sa.Text(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'base_path')
    op.drop_table('drift_finding')
    op.drop_table('response')
    op.drop_table('request')
    # ### end Alembic commands ###
